spring:
  application:
    name: gateway

  cloud:
    gateway:
      globalcors:
        globalcors:
          cors-configurations:
            '[/**]':
              allowedOrigins: "localhost: 3000"
              allowedMethods:
                - GET
                - POST
      discovery:
        locator:
          enabled: true
      routes:
        - id: course
          uri: lb://course
          predicates:
            - Path=/course/**
        - id: file
          uri: lb://file
          predicates:
            - Path=/file/**

server:
  port: 9000

eureka:
  clent:
    service-url:
      defaultZone: http://localhost:8761/eureka
