spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: course_system
          uri: http://localhost:9001
          predicates:
            - Path=/course/**

server:
  port: 9000

eureka:
  clent:
    service-url:
      defaultZone: http://localhost:8761/eureka

